### PR TITLE
Improve the ability of the build system to generate cross-compilers

### PR DESCRIPTION
**Pull request by shym**
This self-PR is gather some preliminary feedback on that work, before opening a PR on `ocaml/ocaml`.
I’ve tested this PR among other things by building a cross-compiler amd64 linux to MinGW64 with:

```
# installing a flexlink in $PATH
# and then running:
$ ./configure --target=x86_64-w64-mingw32 --without-flexdll
$ make cross.opt
<crash>
$ vim runtime/build_config.h # to add the `L` for a Windows string,
  # as sak is not cross-compiler aware
$ make cross.opt

# test
$ ./ocamlopt.opt.exe -nostdlib -I stdlib hello.ml -verbose -o hello.exe
# copy to some Windows, run and rejoice
```

cc @dra27, @shindere, @toots

----

This PR is about making OCaml cross-compilers easier to build.

Recall that building a compiler involves 3 system types described by triplets:

- `build`: the machine on which the compiler is built, usually automatically detected by autoconf's configure
- `host`: the machine on which the compiler will run,
- `target`: the machine on which the code generated by the compiler will run.

So when `build` ≠ `host`, we are cross-compiling. When `host` ≠ `target`, we are building a cross-compiler. This PR aims to improve the cross-compiler story.

Currently, the only supported configurations are when `build` ≈ `host` = `target`, where by “≈” I mean that the code generated for `host` runs on `build` even when they differ (such as when `build` is cygwin and `host` is windows (MSVC) or MinGW).

Even though this is not officially supported yet, many projects use OCaml cross-compilers (Mirage, opam-cross-X, {>> TODO Others? <<}). All those projects generate a cross-compiler by assuming a non-cross OCaml compiler is available in `PATH` (where non-cross means generating code that will run on `build` and `host`).

This PR proposes improvements for building cross compilers, mostly by:

- disambiguating `host` and `target` in configure, where currently most tests about `host` are really testing `target`,
- {>> TODO Should this commit be dropped? <<} sharing a `cross.opt` make target that drives the build of a cross-compiler to deduplicate that work from all cross-compiler projects.

Note that the disambiguation between `host` and `target` in configure should be transparent for all currently supported cases and that it is required to get a fully cross-compatible compiler.

{>> TODO The disambiguation is probably incomplete still: in some cases I’m not so sure, in some cases we need really to test both <<}

### CODE REVIEW

**Comment by toots** [comment]
This is a great idea. Your description of the context is on point. It would be really cool to have this capability supported in the upstream build system up-front.

The details below are provided in case this can help you. I haven't had a chance to look at your changes in details yet.

We shouldn't be too far from native cross-compiler support! With the latest release, I was able to build the cross-compiler by calling specific makefile targets in specific order with specific variables without touching any of the auto-generated files. See: https://github.com/ocaml-cross/opam-cross-windows/blob/main/packages/ocaml-windows64/ocaml-windows64.5.1.1/files/build.sh

There's a little bit more wrangling to get the binaries to install where they need to be and with the standard host-prefix in the install script: https://github.com/ocaml-cross/opam-cross-windows/blob/main/packages/ocaml-windows64/ocaml-windows64.5.1.1/files/install.sh

There still are a few patches: https://github.com/ocaml-cross/opam-cross-windows/tree/main/packages/ocaml-windows64/ocaml-windows64.5.1.1/files/patches

The one for `configure` I'm sure you can include it in your changes. The one to report the proper `os_type` is more interesting. There were some investigations done in `2020` about it without much luck: https://github.com/ocaml-cross/opam-cross-windows/issues/169

**Comment by shym** [comment]
@toots: Thank you very much for your feedback!

> With the latest release, I was able to build the cross-compiler by calling specific makefile targets in specific order with specific variables without touching any of the auto-generated files.

That’s also the goal of `cross.opt` in `Makefile.cross`.
They’re not that easy to compare, in part because probably not all overrides are always necessary in `Makefile.cross`, because the order is not always significant and because they do not build exactly the same targets. IIUC one interesting difference is the fact that `Makefile.cross` builds the `ocamlopt.opt` cross compiler.

> There's a little bit more wrangling to get the binaries to install where they need to be and with the standard host-prefix in the install script: [...]

My `cross-install` target is not as neat. I must admit I’ve been mostly using a [script] that tricks `make install` into generating fragments of an opam `.install` file to use its `?` feature, that tells opam to skip non-existing files: this is handy to avoid generating components of the compiler that are not really useful in the cross compiler (such as `ocamlyacc`, etc.).

[script]: https://github.com/shym/ocaml-solo5/blob/ocaml-5.2-reb/gen_ocaml_install.sh

> There still are a few patches: https://github.com/ocaml-cross/opam-cross-windows/tree/main/packages/ocaml-windows64/ocaml-windows64.5.1.1/files/patches
> 
> The one for `configure` I'm sure you can include it in your changes.

IIUC, the `gcc_eh` changes were already upstreamed by your #12996 PR; and the call out to `cmd` to look for `flexlink` is now triggered only when the build machine is MSYS or Cygwin, so it should work.

> The one to report the proper `os_type` is more interesting. There were some investigations done in `2020` about it without much luck: https://github.com/ocaml-cross/opam-cross-windows/issues/169

Indeed, there is much there. Taking it piecewise:

> ```diff
> diff --git a/middle_end/closure/closure.ml b/middle_end/closure/closure.ml
> index b4095b7237..62d67b17d7 100644
> --- a/middle_end/closure/closure.ml
> +++ b/middle_end/closure/closure.ml
> @@ -1080,9 +1080,9 @@ let rec close ({ backend; fenv; cenv ; mutable_vars } as env) lam =
>          | Word_size -> make_const_int (8*B.size_int)
>          | Int_size -> make_const_int (8*B.size_int - 1)
>          | Max_wosize -> make_const_int ((1 lsl ((8*B.size_int) - 10)) - 1 )
> -        | Ostype_unix -> make_const_bool (Sys.os_type = "Unix")
> -        | Ostype_win32 -> make_const_bool (Sys.os_type = "Win32")
> -        | Ostype_cygwin -> make_const_bool (Sys.os_type = "Cygwin")
> +        | Ostype_unix -> make_const_bool false
> +        | Ostype_win32 -> make_const_bool true
> +        | Ostype_cygwin -> make_const_bool false
>          | Backend_type ->
>              make_const_int 0 (* tag 0 is the same as Native here *)
>        in
> ```

Good point! I was getting:

```
OS type: Win32
Unix: true
Win: false
Cygwin: false
```

which is admittedly unsettling. I have added a commit that will compute the value during `configure` but I don’t know enough about the rationale of using primitives to be sure it would be good. I think I heard using a primitive for the backend type allow `js_of_ocaml` to rebind its value, maybe it does so also for the OS type.

> ```diff
> diff --git a/utils/config.common.ml b/utils/config.common.ml
> index d4850ffd50..182046f38b 100644
> --- a/utils/config.common.ml
> +++ b/utils/config.common.ml
> @@ -64,11 +64,7 @@ let lazy_tag = 246
>  let max_young_wosize = 256
>  let stack_threshold = 32 (* see runtime/caml/config.h *)
>  let stack_safety_margin = 6
> -let default_executable_name =
> -  match Sys.os_type with
> -    "Unix" -> "a.out"
> -  | "Win32" | "Cygwin" -> "camlprog.exe"
> -  | _ -> "camlprog"
> +let default_executable_name = "camlprog.exe"
>  type configuration_value =
>    | String of string
>    | Int of int
> @@ -107,7 +103,7 @@ let configuration_variables () =
>    p "ext_asm" ext_asm;
>    p "ext_lib" ext_lib;
>    p "ext_dll" ext_dll;
> -  p "os_type" Sys.os_type;
> +  p "os_type" "Win32";
>    p "default_executable_name" default_executable_name;
>    p_bool "systhread_supported" systhread_supported;
>    p "host" host;
> ```

Are those changes really important? I mean, do we have workflows that rely on these values to be about the target rather than the host?
They are, luckily, again in a module that is processed by `configure`, so we could compute those values there also.

> ```diff
> diff --git a/utils/config.generated.ml.in b/utils/config.generated.ml.in
> index 83d99afaa3..60708e888e 100644
> --- a/utils/config.generated.ml.in
> +++ b/utils/config.generated.ml.in
> @@ -96,7 +96,7 @@ let asm_cfi_supported = @asm_cfi_supported@
>  let with_frame_pointers = @frame_pointers@
>  let reserved_header_bits = @reserved_header_bits@
> 
> -let ext_exe = {@QS@|@exeext@|@QS@}
> +let ext_exe = ".exe"
>  let ext_obj = "." ^ {@QS@|@OBJEXT@|@QS@}
>  let ext_asm = "." ^ {@QS@|@S@|@QS@}
>  let ext_lib = "." ^ {@QS@|@libext@|@QS@}
> 
> ```

This is computed correctly already on that branch.

**Comment by shym** [comment]
Opened upstream as 13526.

**Comment by toots** [comment]
That looks pretty impressive. Will see if I have comments there. Thanks for the hard work!

**Comment by shym** [comment]
Thank you!

**Pull request closed without merging**
